<?php
/**
 * Optimized classmap autoloader for scoped vendor packages.
 *
 * Auto-generated by generate-autoload.php — do not edit manually.
 *
 * @package TinySolutions\mlt
 */

// Do not allow directly accessing this file.
if ( ! defined( 'ABSPATH' ) ) {
	exit( 'This script cannot be accessed directly.' );
}

spl_autoload_register(
	function ( $class ) {
		// Optimized classmap — O(1) lookup.
		static $classmap = [
		'TinySolutions\\mlt\\Abs\\Discount' => __DIR__ . '/app/Abs/Discount.php',
		'TinySolutions\\mlt\\Controllers\\AI\\AiApi' => __DIR__ . '/app/Controllers/AI/AiApi.php',
		'TinySolutions\\mlt\\Controllers\\Admin\\Api' => __DIR__ . '/app/Controllers/Admin/Api.php',
		'TinySolutions\\mlt\\Controllers\\Admin\\RegisterPostAndTax' => __DIR__ . '/app/Controllers/Admin/RegisterPostAndTax.php',
		'TinySolutions\\mlt\\Controllers\\Admin\\SubMenu' => __DIR__ . '/app/Controllers/Admin/SubMenu.php',
		'TinySolutions\\mlt\\Controllers\\AssetsController' => __DIR__ . '/app/Controllers/AssetsController.php',
		'TinySolutions\\mlt\\Controllers\\Dependencies' => __DIR__ . '/app/Controllers/Dependencies.php',
		'TinySolutions\\mlt\\Controllers\\Hooks\\ActionHooks' => __DIR__ . '/app/Controllers/Hooks/ActionHooks.php',
		'TinySolutions\\mlt\\Controllers\\Hooks\\Ajax' => __DIR__ . '/app/Controllers/Hooks/Ajax.php',
		'TinySolutions\\mlt\\Controllers\\Hooks\\CronJobHooks' => __DIR__ . '/app/Controllers/Hooks/CronJobHooks.php',
		'TinySolutions\\mlt\\Controllers\\Hooks\\FilterHooks' => __DIR__ . '/app/Controllers/Hooks/FilterHooks.php',
		'TinySolutions\\mlt\\Controllers\\Installation' => __DIR__ . '/app/Controllers/Installation.php',
		'TinySolutions\\mlt\\Controllers\\Notice\\Review' => __DIR__ . '/app/Controllers/Notice/Review.php',
		'TinySolutions\\mlt\\Controllers\\Notice\\SpecialDiscount' => __DIR__ . '/app/Controllers/Notice/SpecialDiscount.php',
		'TinySolutions\\mlt\\Helpers\\Fns' => __DIR__ . '/app/Helpers/Fns.php',
		'TinySolutions\\mlt\\Modules\\DownloadMedia' => __DIR__ . '/app/Modules/DownloadMedia.php',
		'TinySolutions\\mlt\\Modules\\Duplicate\\DuplicateScanner' => __DIR__ . '/app/Modules/Duplicate/DuplicateScanner.php',
		'TinySolutions\\mlt\\Modules\\ImageSize\\ImageSizeModule' => __DIR__ . '/app/Modules/ImageSize/ImageSizeModule.php',
		'TinySolutions\\mlt\\Modules\\ModuleInit' => __DIR__ . '/app/Modules/ModuleInit.php',
		'TinySolutions\\mlt\\Modules\\Regenerate\\RegenerateThumbnails' => __DIR__ . '/app/Modules/Regenerate/RegenerateThumbnails.php',
		'TinySolutions\\mlt\\Modules\\Rename\\RenameModule' => __DIR__ . '/app/Modules/Rename/RenameModule.php',
		'TinySolutions\\mlt\\Modules\\Rubbish\\RubbishScanner' => __DIR__ . '/app/Modules/Rubbish/RubbishScanner.php',
		'TinySolutions\\mlt\\Modules\\UsedWhere\\UsedWhereScanner' => __DIR__ . '/app/Modules/UsedWhere/UsedWhereScanner.php',
		'TinySolutions\\mlt\\Traits\\SingletonTrait' => __DIR__ . '/app/Traits/SingletonTrait.php',
		'TinySolutions\\mlt\\Tsmlt' => __DIR__ . '/app/Tsmlt.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Api\\AlterInterface' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Api/AlterInterface.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Api\\CreateInterface' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Api/CreateInterface.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Api\\DeleteInterface' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Api/DeleteInterface.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Api\\SelectInterface' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Api/SelectInterface.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Api\\TableInterface' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Api/TableInterface.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Api\\UpdateInterface' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Api/UpdateInterface.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Api\\WhereClauseInterface' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Api/WhereClauseInterface.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Clause\\JoinClause' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Clause/JoinClause.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Clause\\SqlCore' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Clause/SqlCore.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Clause\\SubQuery' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Clause/SubQuery.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Clause\\WhereClause' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Clause/WhereClause.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Connect' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Connect.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\DB' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/DB.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\QueryFactory' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/QueryFactory.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\SqlGenerator' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/SqlGenerator.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Statement\\Alter' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Statement/Alter.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Statement\\Create' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Statement/Create.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Statement\\Delete' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Statement/Delete.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Statement\\Insert' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Statement/Insert.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Statement\\Select' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Statement/Select.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Statement\\Table' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Statement/Table.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Statement\\Update' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Statement/Update.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Utilities' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Utilities.php',
		'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\Validation\\IdentifierValidator' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/Validation/IdentifierValidator.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\ElementReference\\Resolver' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/ElementReference/Resolver.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\ElementReference\\Subject' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/ElementReference/Subject.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\ElementReference\\Usage' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/ElementReference/Usage.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\Exceptions\\NestingException' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/Exceptions/NestingException.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\Helper' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/Helper.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\Sanitizer' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/Sanitizer.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\data\\AllowedAttributes' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/data/AllowedAttributes.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\data\\AllowedTags' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/data/AllowedTags.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\data\\AttributeInterface' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/data/AttributeInterface.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\data\\TagInterface' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/data/TagInterface.php',
		'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\data\\XPath' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/data/XPath.php',
		];

		if ( isset( $classmap[ $class ] ) ) {
			require $classmap[ $class ];
			return;
		}

		// PSR-4 fallback for unlisted classes.
		static $psr4 = [
			'TinySolutions\\mlt\\' => __DIR__ . '/app/',
			'TinySolutions\\mlt\\Vendor\\CodesVault\\Howdyqb\\' => __DIR__ . '/vendor_prefixed/codesvault/howdy-qb/src/',
			'TinySolutions\\mlt\\Vendor\\enshrined\\svgSanitize\\' => __DIR__ . '/vendor_prefixed/enshrined/svg-sanitize/src/',
		];

		foreach ( $psr4 as $prefix => $base_dir ) {
			$len = strlen( $prefix );
			if ( strncmp( $prefix, $class, $len ) !== 0 ) {
				continue;
			}
			$relative_class = substr( $class, $len );
			$file           = $base_dir . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
				return;
			}
		}
	}
);
