<?php
/**
 * Generates autoload.php after PHP-Scoper runs.
 *
 * @phpcs:disable WordPress.Security.EscapeOutput -- CLI script, not a web request.
 *
 * Scans vendor_prefixed/ for scoped packages and builds a standalone
 * PSR-4 autoloader so the vendor/ directory is not needed in production.
 *
 * Usage: Called automatically by `composer prefix-vendor`
 *
 * @package TinySolutions\mlt
 */

$prefix = 'TinySolutions\\mlt\\Vendor';

// Discover scoped packages from vendor_prefixed directory.
$map = [
	'TinySolutions\\mlt\\' => '/app/',
];

$vendorPrefixedDir = __DIR__ . '/vendor_prefixed';

foreach ( glob( $vendorPrefixedDir . '/*/*/composer.json' ) as $composerFile ) {
	$json = json_decode( file_get_contents( $composerFile ), true );

	if ( empty( $json['autoload']['psr-4'] ) ) {
		continue;
	}

	$packageDir = dirname( $composerFile );
	$relPath    = str_replace( __DIR__, '', $packageDir );

	foreach ( $json['autoload']['psr-4'] as $namespace => $src ) {
		// Namespace is already prefixed by PHP-Scoper in the scoped composer.json.
		$srcPath          = rtrim( $relPath, '/' ) . '/' . rtrim( $src, '/' ) . '/';
		$map[ $namespace ] = $srcPath;
	}
}

// Generate autoload.php content.
$entries = '';
foreach ( $map as $ns => $dir ) {
	$escapedNs  = addcslashes( $ns, '\\' );
	$entries   .= "\t\t\t'{$escapedNs}' => __DIR__ . '{$dir}',\n";
}

$content = <<<'HEADER'
<?php
/**
 * Standalone PSR-4 autoloader for prefixed vendor packages.
 *
 * Auto-generated by generate-autoload.php — do not edit manually.
 *
 * @package TinySolutions\mlt
 */

// Do not allow directly accessing this file.
if ( ! defined( 'ABSPATH' ) ) {
	exit( 'This script cannot be accessed directly.' );
}

spl_autoload_register(
	function ( $class ) {
		$map = [

HEADER;

$content .= $entries;

$content .= <<<'FOOTER'
		];

		foreach ( $map as $prefix => $base_dir ) {
			$len = strlen( $prefix );
			if ( strncmp( $prefix, $class, $len ) !== 0 ) {
				continue;
			}
			$relative_class = substr( $class, $len );
			$file           = $base_dir . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
				return;
			}
		}
	}
);

FOOTER;

file_put_contents( __DIR__ . '/autoload.php', $content );

echo "autoload.php generated with " . count( $map ) . " namespace mappings.\n";
