<?php
/**
 * Generates autoload.php after PHP-Scoper runs.
 *
 * Scans vendor_prefixed/ for scoped packages and builds a standalone
 * PSR-4 autoloader so the vendor/ directory is not needed in production.
 *
 * Usage: Called automatically by `composer prefix-vendor`
 *
 * @package TinySolutions\mlt
 */

// phpcs:disable WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedVariableFound -- CLI build script, not loaded in WordPress.
// phpcs:disable WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- CLI script.
// phpcs:disable WordPress.Security.EscapeOutput -- CLI script.

$tsmlt_prefix = 'TinySolutions\\mlt\\Vendor';

// Discover scoped packages from vendor_prefixed directory.
$tsmlt_map = [
	'TinySolutions\\mlt\\' => '/app/',
];

$tsmlt_vendor_dir = __DIR__ . '/vendor_prefixed';

foreach ( glob( $tsmlt_vendor_dir . '/*/*/composer.json' ) as $tsmlt_composer_file ) {
	$tsmlt_json = json_decode( file_get_contents( $tsmlt_composer_file ), true );

	if ( empty( $tsmlt_json['autoload']['psr-4'] ) ) {
		continue;
	}

	$tsmlt_package_dir = dirname( $tsmlt_composer_file );
	$tsmlt_rel_path    = str_replace( __DIR__, '', $tsmlt_package_dir );

	foreach ( $tsmlt_json['autoload']['psr-4'] as $tsmlt_namespace => $tsmlt_src ) {
		// Namespace is already prefixed by PHP-Scoper in the scoped composer.json.
		$tsmlt_src_path                = rtrim( $tsmlt_rel_path, '/' ) . '/' . rtrim( $tsmlt_src, '/' ) . '/';
		$tsmlt_map[ $tsmlt_namespace ] = $tsmlt_src_path;
	}
}

// Generate autoload.php content.
$tsmlt_entries = '';
foreach ( $tsmlt_map as $tsmlt_ns => $tsmlt_dir ) {
	$tsmlt_escaped_ns  = addcslashes( $tsmlt_ns, '\\' );
	$tsmlt_entries    .= "\t\t\t'{$tsmlt_escaped_ns}' => __DIR__ . '{$tsmlt_dir}',\n";
}

$tsmlt_content = <<<'HEADER'
<?php
/**
 * Standalone PSR-4 autoloader for prefixed vendor packages.
 *
 * Auto-generated by generate-autoload.php — do not edit manually.
 *
 * @package TinySolutions\mlt
 */

// Do not allow directly accessing this file.
if ( ! defined( 'ABSPATH' ) ) {
	exit( 'This script cannot be accessed directly.' );
}

spl_autoload_register(
	function ( $class ) {
		$map = [

HEADER;

$tsmlt_content .= $tsmlt_entries;

$tsmlt_content .= <<<'FOOTER'
		];

		foreach ( $map as $prefix => $base_dir ) {
			$len = strlen( $prefix );
			if ( strncmp( $prefix, $class, $len ) !== 0 ) {
				continue;
			}
			$relative_class = substr( $class, $len );
			$file           = $base_dir . str_replace( '\\', '/', $relative_class ) . '.php';
			if ( file_exists( $file ) ) {
				require $file;
				return;
			}
		}
	}
);

FOOTER;

file_put_contents( __DIR__ . '/autoload.php', $tsmlt_content );

echo 'autoload.php generated with ' . count( $tsmlt_map ) . " namespace mappings.\n";
