import { useState } from 'react';
import { createPortal } from 'react-dom';
import { notifications } from '@/js/Utils/Data';
import ProLabel from '@/js/Component/Badges/ProLabel';
import Axios from 'axios';

interface AiButtonProps {
    attachmentId: number;
    fieldType: 'title' | 'alt_text' | 'caption' | 'description' | 'filename';
    onSuccess: (value: string) => void;
    className?: string;
}

export default function AiButton({ attachmentId, fieldType, onSuccess, className = '' }: AiButtonProps) {
    const [loading, setLoading] = useState(false);
    const [suggestions, setSuggestions] = useState<string[]>([]);
    // Modal visibility is tracked separately from `suggestions` so it can open
    // before anything is generated — the user gets to write an instruction first.
    const [open, setOpen] = useState(false);
    // One-off instruction for this image only; intentionally not persisted, and
    // cleared when the modal closes so it never carries over to another image.
    const [instruction, setInstruction] = useState('');
    // Inline upgrade notice, shown when a free user clicks the instruction field.
    const [showUpgrade, setShowUpgrade] = useState(false);

    const isPro = !!tsmltParams.hasExtended;

    const closeModal = () => {
        setOpen(false);
        setSuggestions([]);
        setInstruction('');
        setShowUpgrade(false);
    };

    const handleGenerate = async () => {
        setSuggestions([]);
        setLoading(true);
        try {
            const body = new URLSearchParams({
                action: 'tsmlt_ai_generate',
                nonce: tsmltParams.tsmlt_wpnonce,
                params: JSON.stringify({
                    attachment_id: attachmentId,
                    field_type: fieldType,
                    instruction: instruction.trim(),
                }),
            });
            const response = await Axios.post(tsmltParams.ajaxUrl, body);
            const envelope = response.data;
            if (envelope && envelope.success && Array.isArray(envelope.data?.suggestions) && envelope.data.suggestions.length) {
                const raw = envelope.data.suggestions as string[];
                if (!isPro) {
                    const placeholders = [
                        'Another descriptive suggestion will appear here',
                        'A different option generated by AI',
                        'Alternative content idea for your media',
                        'More AI-generated suggestions available',
                    ];
                    setSuggestions([raw[0], ...placeholders]);
                } else {
                    setSuggestions(raw);
                }
            } else {
                const message = envelope?.data?.message || 'AI generation failed. Check your API key.';
                notifications(false, message);
            }
        } catch {
            notifications(false, 'AI generation failed. Check your API key.');
        } finally {
            setLoading(false);
        }
    };

    const handleSelect = (value: string) => {
        onSuccess(value);
        closeModal();
    };

    const fieldLabel = fieldType.replace(/_/g, ' ');

    return (
        <div className={`${className}`}>
            <button
                type="button"
                onClick={() => setOpen(true)}
                disabled={loading}
                title={`Generate ${fieldLabel} with AI`}
                className="inline-flex text-purple-700 items-center justify-center gap-0.5 w-12 h-8.5 bg-purple-50 border border-purple-200 rounded hover:bg-purple-100 disabled:opacity-50 cursor-pointer text-xs font-semibold"
            >
                {loading ? (
                    <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                ) : (
                    <>
                        <svg className="w-3.5 h-3.5 text-purple-500" fill="currentColor" viewBox="0 0 24 24">
                            <path d="M12 2l2.4 7.2H22l-6 4.8 2.4 7.2L12 16.4l-6.4 4.8L8 14 2 9.2h7.6z" />
                        </svg>
                        AI
                    </>
                )}
            </button>

            {open && createPortal(
                <div className="fixed inset-0 flex items-center justify-center" style={{ zIndex: 999999 }}>
                    {/* Backdrop */}
                    <div
                        className="absolute inset-0 bg-black/40"
                        onClick={closeModal}
                    />

                    {/* Modal panel */}
                    <div className="relative bg-white rounded-xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden">

                        {/* Header */}
                        <div className="flex items-center justify-between px-5 py-3.5">
                            <div className="flex items-center gap-2">
                                <span className="inline-flex items-center justify-center w-6 h-6 rounded-md bg-purple-100">
                                    <svg className="w-3.5 h-3.5 text-purple-600" fill="currentColor" viewBox="0 0 24 24">
                                        <path d="M12 2l2.4 7.2H22l-6 4.8 2.4 7.2L12 16.4l-6.4 4.8L8 14 2 9.2h7.6z" />
                                    </svg>
                                </span>
                                <span className="text-sm font-semibold text-gray-800 capitalize">
                                    AI Suggestions — {fieldLabel}
                                </span>
                            </div>
                            <button
                                type="button"
                                onClick={closeModal}
                                className="p-1 text-gray-400 hover:text-gray-600 cursor-pointer transition-colors rounded"
                            >
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>

                        {/* One-off instruction for this image, then generate */}
                        <div className="px-5 pt-3 pb-3.5">
                            <label className="flex items-center gap-1.5 text-xs font-medium text-gray-500 mb-1.5">
                                Extra instruction for this image
                                <span className="text-gray-300">(optional)</span>
                                {!isPro && <ProLabel />}
                            </label>
                            <textarea
                                rows={2}
                                value={instruction}
                                // readOnly rather than disabled: a disabled field swallows
                                // click events, so the upgrade hint would never appear.
                                readOnly={!isPro}
                                onChange={(e) => { if (isPro) setInstruction(e.target.value); }}
                                // Reveal an inline notice instead of navigating away — the user
                                // is mid-edit, and opening a tab here loses their place.
                                onClick={() => { if (!isPro) setShowUpgrade(true); }}
                                placeholder={isPro
                                    ? 'e.g. Emphasise the grey fabric and mention it is height-adjustable.'
                                    : 'Custom instructions are a Pro feature.'}
                                className={`w-full px-3 py-2 text-sm border rounded-lg resize-none transition-shadow focus:ring-2 focus:ring-purple-500/40 focus:border-purple-400 focus:outline-none ${
                                    isPro
                                        ? 'border-gray-200 placeholder:text-gray-300'
                                        : 'border-gray-200 bg-gray-50 text-gray-400 cursor-pointer placeholder:text-gray-400'
                                }`}
                            />

                            {!isPro && showUpgrade && (
                                <div className="mt-2 flex items-start gap-2 px-3 py-2 text-[11px] leading-snug text-amber-800 bg-amber-50 border border-amber-200 rounded-lg">
                                    <svg className="w-3.5 h-3.5 shrink-0 mt-px" fill="currentColor" viewBox="0 0 20 20">
                                        <path fillRule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clipRule="evenodd" />
                                    </svg>
                                    <span>
                                        Custom instructions are a Pro feature.{' '}
                                        <a
                                            href={tsmltParams.proLink}
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            className="font-semibold underline hover:no-underline"
                                        >
                                            Upgrade to Pro
                                        </a>{' '}
                                        to guide each generation. You can still generate using your default settings.
                                    </span>
                                </div>
                            )}

                            <div className="flex items-center justify-between gap-3 mt-2.5">
                                <p className="text-[11px] leading-snug text-gray-400">
                                    {isPro
                                        ? 'Applies to this generation only — not saved.'
                                        : 'Generation uses your default settings.'}
                                </p>
                                <button
                                    type="button"
                                    onClick={handleGenerate}
                                    disabled={loading}
                                    className="shrink-0 inline-flex items-center justify-center gap-1.5 px-4 py-2 text-sm font-medium text-white bg-purple-600 rounded-lg shadow-sm hover:bg-purple-700 active:bg-purple-800 disabled:opacity-60 disabled:cursor-default cursor-pointer transition-colors"
                                >
                                    {loading ? (
                                        <svg className="w-3.5 h-3.5 animate-spin" fill="none" viewBox="0 0 24 24">
                                            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                                            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                                        </svg>
                                    ) : (
                                        <svg className="w-3.5 h-3.5" fill="currentColor" viewBox="0 0 24 24">
                                            <path d="M12 2l2.4 7.2H22l-6 4.8 2.4 7.2L12 16.4l-6.4 4.8L8 14 2 9.2h7.6z" />
                                        </svg>
                                    )}
                                    {loading ? 'Generating…' : suggestions.length ? 'Regenerate' : 'Generate'}
                                </button>
                            </div>
                        </div>

                        {/* Suggestions list */}
                        {(suggestions.length > 0 || loading) && (
                        <div className="border-t border-gray-100 divide-y divide-gray-100 max-h-[50vh] overflow-y-auto">
                            {loading && !suggestions.length && (
                                <div className="px-5 py-3 space-y-2">
                                    {[0, 1, 2].map((i) => (
                                        <div key={i} className="flex items-center gap-3 animate-pulse">
                                            <span className="shrink-0 w-4 h-4 rounded-full bg-gray-100" />
                                            <span className="h-2.5 rounded bg-gray-100" style={{ width: `${80 - i * 15}%` }} />
                                        </div>
                                    ))}
                                </div>
                            )}
                            {suggestions.map((s, i) => {
                                const isLocked = !isPro && i > 0;
                                return (
                                    <button
                                        key={i}
                                        type="button"
                                        onClick={() => isLocked ? window.open(tsmltParams.proLink, '_blank') : handleSelect(s)}
                                        className={`relative w-full text-left px-5 py-3.5 transition-colors cursor-pointer ${
                                            isLocked
                                                ? 'bg-gray-50'
                                                : 'hover:bg-purple-50 active:bg-purple-100'
                                        }`}
                                    >
                                        <div className="flex items-start gap-3">
                                            <span className={`shrink-0 inline-flex items-center justify-center w-5 h-5 rounded-full text-[11px] font-bold mt-0.5 ${
                                                isLocked ? 'bg-gray-200 text-gray-400' : 'bg-purple-100 text-purple-700'
                                            }`}>
                                                {i + 1}
                                            </span>
                                            {isLocked ? (
                                                <span className="flex-1 min-w-0">
                                                    <span className="blur-[3px] select-none text-sm text-gray-700 leading-relaxed block">
                                                        {s}
                                                    </span>
                                                    <span className="inline-flex items-center gap-1 mt-1 px-2 py-0.5 text-[11px] font-semibold text-amber-700 bg-amber-50 border border-amber-200 rounded-full">
                                                        <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                                                            <path fillRule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clipRule="evenodd" />
                                                        </svg>
                                                        Pro only — click to upgrade
                                                    </span>
                                                </span>
                                            ) : (
                                                <span className="flex-1 min-w-0 text-sm text-gray-800 leading-relaxed">
                                                    {s}
                                                </span>
                                            )}

                                            {!isLocked && (
                                                <svg className="w-4 h-4 shrink-0 text-purple-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                                                </svg>
                                            )}
                                        </div>
                                    </button>
                                );
                            })}
                        </div>
                        )}

                        {/* Footer */}
                        <div className="px-5 py-2.5 border-t border-gray-100 bg-gray-50/70 flex items-center justify-between">
                            <span className="text-xs text-gray-400">
                                {suggestions.length ? 'Click a suggestion to apply it' : ''}
                            </span>
                            <button
                                type="button"
                                onClick={closeModal}
                                className="text-xs text-gray-500 hover:text-gray-700 cursor-pointer font-medium"
                            >
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>,
                document.body
            )}
        </div>
    );
}
