import { useState } from 'react';
import { notifications } from '@/js/Utils/Data';
import Axios from 'axios';

interface AiButtonProps {
    attachmentId: number;
    fieldType: 'title' | 'alt_text' | 'caption' | 'description' | 'filename';
    onSuccess: (value: string) => void;
    className?: string;
}

export default function AiButton({ attachmentId, fieldType, onSuccess, className = '' }: AiButtonProps) {
    const [loading, setLoading] = useState(false);
    const [suggestions, setSuggestions] = useState<string[]>([]);

    const isPro = !!tsmltParams.hasExtended;

    const handleClick = async () => {
        setSuggestions([]);
        setLoading(true);
        try {
            const body = new URLSearchParams({
                action: 'tsmlt_ai_generate',
                nonce: tsmltParams.tsmlt_wpnonce,
                params: JSON.stringify({ attachment_id: attachmentId, field_type: fieldType }),
            });
            const response = await Axios.post(tsmltParams.ajaxUrl, body);
            const envelope = response.data;
            if (envelope && envelope.success && Array.isArray(envelope.data?.suggestions) && envelope.data.suggestions.length) {
                const raw = envelope.data.suggestions as string[];
                if (!isPro) {
                    const placeholders = [
                        'Another descriptive suggestion will appear here',
                        'A different option generated by AI',
                        'Alternative content idea for your media',
                        'More AI-generated suggestions available',
                    ];
                    setSuggestions([raw[0], ...placeholders]);
                } else {
                    setSuggestions(raw);
                }
            } else {
                const message = envelope?.data?.message || 'AI generation failed. Check your API key.';
                notifications(false, message);
            }
        } catch {
            notifications(false, 'AI generation failed. Check your API key.');
        } finally {
            setLoading(false);
        }
    };

    const handleSelect = (value: string) => {
        onSuccess(value);
        setSuggestions([]);
    };

    return (
        <div className={`${className}`}>
            <button
                type="button"
                onClick={handleClick}
                disabled={loading}
                title={`Generate ${fieldType.replace('_', ' ')} with AI`}
                className="inline-flex text-purple-700 items-center justify-center w-10 h-7 bg-purple-50 border border-purple-200 rounded hover:bg-purple-100 disabled:opacity-50 cursor-pointer"
            >
                {loading ? (
                    <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                ) : (
                   <>
                       <span className="text-sm leading-none text-blue-600">✨</span>  {loading ? 'Generating...' : 'AI'}
                   </>
                )}
            </button>

            {suggestions.length > 0 && (
                <div className="absolute z-[9999] top-full mt-1 left-0 w-80 bg-white border border-purple-200 rounded-md shadow-lg">
                    <div className="flex items-center justify-between px-3 py-2 border-b border-gray-100">
                        <span className="text-xs font-semibold text-purple-700">Select a suggestion</span>
                        <button
                            type="button"
                            onClick={() => setSuggestions([])}
                            className="text-gray-400 hover:text-gray-600 text-xs cursor-pointer"
                        >
                            ✕
                        </button>
                    </div>
                    {suggestions.map((s, i) => {
                        const isLocked = !isPro && i > 0;
                        return (
                            <button
                                key={i}
                                type="button"
                                onClick={() => isLocked ? window.open(tsmltParams.proLink, '_blank') : handleSelect(s)}
                                className={`relative block w-full text-left px-3 py-2 text-sm border-b border-gray-100 last:border-b-0 cursor-pointer ${isLocked ? 'select-none' : 'text-gray-700 hover:bg-purple-50'}`}
                            >
                                {isLocked ? (
                                    <>
                                        <span className="blur-[3px] pointer-events-none">
                                            <span className="font-semibold text-purple-600 mr-2">{i + 1}.</span>{s}
                                        </span>
                                        <span className="absolute inset-0 flex items-center justify-center">
                                            <span className="inline-flex items-center gap-1 px-2 py-0.5 text-xs font-semibold text-amber-700 bg-amber-50 border border-amber-200 rounded">
                                                Pro
                                            </span>
                                        </span>
                                    </>
                                ) : (
                                    <>
                                        <span className="font-semibold text-purple-600 mr-2">{i + 1}.</span>{s}
                                    </>
                                )}
                            </button>
                        );
                    })}
                </div>
            )}
        </div>
    );
}
