import { useState } from 'react';
import { createPortal } from 'react-dom';
import { notifications } from '@/js/Utils/Data';
import Axios from 'axios';

interface AiButtonProps {
    attachmentId: number;
    fieldType: 'title' | 'alt_text' | 'caption' | 'description' | 'filename';
    onSuccess: (value: string) => void;
    className?: string;
}

export default function AiButton({ attachmentId, fieldType, onSuccess, className = '' }: AiButtonProps) {
    const [loading, setLoading] = useState(false);
    const [suggestions, setSuggestions] = useState<string[]>([]);

    const isPro = !!tsmltParams.hasExtended;

    const handleClick = async () => {
        setSuggestions([]);
        setLoading(true);
        try {
            const body = new URLSearchParams({
                action: 'tsmlt_ai_generate',
                nonce: tsmltParams.tsmlt_wpnonce,
                params: JSON.stringify({ attachment_id: attachmentId, field_type: fieldType }),
            });
            const response = await Axios.post(tsmltParams.ajaxUrl, body);
            const envelope = response.data;
            if (envelope && envelope.success && Array.isArray(envelope.data?.suggestions) && envelope.data.suggestions.length) {
                const raw = envelope.data.suggestions as string[];
                if (!isPro) {
                    const placeholders = [
                        'Another descriptive suggestion will appear here',
                        'A different option generated by AI',
                        'Alternative content idea for your media',
                        'More AI-generated suggestions available',
                    ];
                    setSuggestions([raw[0], ...placeholders]);
                } else {
                    setSuggestions(raw);
                }
            } else {
                const message = envelope?.data?.message || 'AI generation failed. Check your API key.';
                notifications(false, message);
            }
        } catch {
            notifications(false, 'AI generation failed. Check your API key.');
        } finally {
            setLoading(false);
        }
    };

    const handleSelect = (value: string) => {
        onSuccess(value);
        setSuggestions([]);
    };

    const fieldLabel = fieldType.replace(/_/g, ' ');

    return (
        <div className={`${className}`}>
            <button
                type="button"
                onClick={handleClick}
                disabled={loading}
                title={`Generate ${fieldLabel} with AI`}
                className="inline-flex text-purple-700 items-center justify-center gap-0.5 w-12 h-8.5 bg-purple-50 border border-purple-200 rounded hover:bg-purple-100 disabled:opacity-50 cursor-pointer text-xs font-semibold"
            >
                {loading ? (
                    <svg className="w-3 h-3 animate-spin" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                    </svg>
                ) : (
                    <>
                        <svg className="w-3.5 h-3.5 text-purple-500" fill="currentColor" viewBox="0 0 24 24">
                            <path d="M12 2l2.4 7.2H22l-6 4.8 2.4 7.2L12 16.4l-6.4 4.8L8 14 2 9.2h7.6z" />
                        </svg>
                        AI
                    </>
                )}
            </button>

            {suggestions.length > 0 && createPortal(
                <div className="fixed inset-0 flex items-center justify-center" style={{ zIndex: 999999 }}>
                    {/* Backdrop */}
                    <div
                        className="absolute inset-0 bg-black/40"
                        onClick={() => setSuggestions([])}
                    />

                    {/* Modal panel */}
                    <div className="relative bg-white rounded-xl shadow-2xl w-full max-w-lg mx-4 overflow-hidden">

                        {/* Header */}
                        <div className="flex items-center justify-between px-5 py-4 border-b border-gray-100 bg-purple-50">
                            <div className="flex items-center gap-2">
                                <svg className="w-4 h-4 text-purple-500" fill="currentColor" viewBox="0 0 24 24">
                                    <path d="M12 2l2.4 7.2H22l-6 4.8 2.4 7.2L12 16.4l-6.4 4.8L8 14 2 9.2h7.6z" />
                                </svg>
                                <span className="text-sm font-semibold text-purple-800 capitalize">
                                    AI Suggestions — {fieldLabel}
                                </span>
                            </div>
                            <button
                                type="button"
                                onClick={() => setSuggestions([])}
                                className="p-1 text-gray-400 hover:text-gray-600 cursor-pointer transition-colors rounded"
                            >
                                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                                </svg>
                            </button>
                        </div>

                        {/* Suggestions list */}
                        <div className="divide-y divide-gray-100 max-h-[60vh] overflow-y-auto">
                            {suggestions.map((s, i) => {
                                const isLocked = !isPro && i > 0;
                                return (
                                    <button
                                        key={i}
                                        type="button"
                                        onClick={() => isLocked ? window.open(tsmltParams.proLink, '_blank') : handleSelect(s)}
                                        className={`relative w-full text-left px-5 py-3.5 transition-colors cursor-pointer ${
                                            isLocked
                                                ? 'bg-gray-50'
                                                : 'hover:bg-purple-50 active:bg-purple-100'
                                        }`}
                                    >
                                        <div className="flex items-start gap-3">
                                            <span className={`shrink-0 inline-flex items-center justify-center w-5 h-5 rounded-full text-[11px] font-bold mt-0.5 ${
                                                isLocked ? 'bg-gray-200 text-gray-400' : 'bg-purple-100 text-purple-700'
                                            }`}>
                                                {i + 1}
                                            </span>
                                            {isLocked ? (
                                                <span className="flex-1 min-w-0">
                                                    <span className="blur-[3px] select-none text-sm text-gray-700 leading-relaxed block">
                                                        {s}
                                                    </span>
                                                    <span className="inline-flex items-center gap-1 mt-1 px-2 py-0.5 text-[11px] font-semibold text-amber-700 bg-amber-50 border border-amber-200 rounded-full">
                                                        <svg className="w-3 h-3" fill="currentColor" viewBox="0 0 20 20">
                                                            <path fillRule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clipRule="evenodd" />
                                                        </svg>
                                                        Pro only — click to upgrade
                                                    </span>
                                                </span>
                                            ) : (
                                                <span className="flex-1 min-w-0 text-sm text-gray-800 leading-relaxed">
                                                    {s}
                                                </span>
                                            )}

                                            {!isLocked && (
                                                <svg className="w-4 h-4 shrink-0 text-purple-400 mt-0.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                                                </svg>
                                            )}
                                        </div>
                                    </button>
                                );
                            })}
                        </div>

                        {/* Footer */}
                        <div className="px-5 py-3 border-t border-gray-100 bg-gray-50 flex items-center justify-between">
                            <span className="text-xs text-gray-400">Click a suggestion to apply it</span>
                            <button
                                type="button"
                                onClick={() => setSuggestions([])}
                                className="text-xs text-gray-500 hover:text-gray-700 cursor-pointer font-medium"
                            >
                                Cancel
                            </button>
                        </div>
                    </div>
                </div>,
                document.body
            )}
        </div>
    );
}
