export const UPDATE_DATA_OPTIONS = 'UPDATE_DATA_OPTIONS';
export const UPDATE_SINGLE_MEDIA = 'UPDATE_SINGLE_MEDIA';
export const UPDATE_RENAMER_MEDIA = 'UPDATE_RENAMER_MEDIA';
export const GENERAL_DATA = 'GENERAL_DATA';
export const GET_MEDIA_LIST = 'GET_MEDIA_LIST';
